#!/bin/sh

if [ ! "$EVERNOTEBOT_DIR" ]; then
	EVERNOTEBOT_DIR="$HOME/evernotebot"
	echo "Variable EVERNOTEBOT_DIR isn't set, so $EVERNOTEBOT_DIR used"
fi

ENV_FILE="$EVERNOTEBOT_DIR/.env"
if [ ! -f "$ENV_FILE" ]; then
	echo "FAILED: File $ENV_FILE not found"
	exit 1
fi

DOCKER_IMAGE_NAME="djudman/evernote-telegram-bot:latest"
DOCKER_CONTAINER_NAME="evernotebot"
LOGS_DIR="$EVERNOTEBOT_DIR/logs"
DATA_DIR="$EVERNOTEBOT_DIR/data"
EVERNOTEBOT_EXPOSE_PORT=8000

start() {
	docker run \
		-e EVERNOTEBOT_DEBUG="$EVERNOTEBOT_DEBUG" \
		-e EVERNOTEBOT_HOSTNAME="$EVERNOTEBOT_HOSTNAME" \
		-e TELEGRAM_API_TOKEN="$TELEGRAM_API_TOKEN" \
		-e TELEGRAM_BOT_NAME="$TELEGRAM_BOT_NAME" \
		-e EVERNOTE_READONLY_KEY="$EVERNOTE_READONLY_KEY" \
		-e EVERNOTE_READONLY_SECRET="$EVERNOTE_READONLY_SECRET" \
		-e EVERNOTE_READWRITE_KEY="$EVERNOTE_READWRITE_KEY" \
		-e EVERNOTE_READWRITE_SECRET="$EVERNOTE_READWRITE_SECRET" \
		--restart=always \
		-d \
		-p 127.0.0.1:$EVERNOTEBOT_EXPOSE_PORT:8000 \
		--name="$DOCKER_CONTAINER_NAME" \
		-v "$LOGS_DIR":/app/logs:rw \
		-v "$DATA_DIR":/app/db:rw \
		"$DOCKER_IMAGE_NAME" > /dev/null 2>&1
	status=$?
	if [ $status -ne 0 ]; then
		echo "FAILED"
		docker rm "$DOCKER_CONTAINER_NAME"
		exit 1
	fi
	echo "Evernotebot started at http://127.0.0.1:$EVERNOTEBOT_EXPOSE_PORT"
}

stop() {
	docker stop "$DOCKER_CONTAINER_NAME" > /dev/null 2>&1
	docker rm "$DOCKER_CONTAINER_NAME" > /dev/null 2>&1
}

restart() {
	stop
	start
}

update() {
	docker pull $DOCKER_IMAGE_NAME
	restart
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	update)
		update
		;;
esac
